# Generated by Django 5.2.8 on 2025-12-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': '商品颜色', 'verbose_name_plural': '商品颜色'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodsdetail',
            options={'verbose_name': '商品详情', 'verbose_name_plural': '商品详情'},
        ),
        migrations.AlterModelOptions(
            name='goodsdetainame',
            options={'verbose_name': '商品详情属性名', 'verbose_name_plural': '商品详情属性名'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '商品库存', 'verbose_name_plural': '商品库存'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': '商品尺寸', 'verbose_name_plural': '商品尺寸'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=10, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='color',
            name='colorname',
            field=models.CharField(max_length=10, verbose_name='颜色名称'),
        ),
        migrations.AlterField(
            model_name='color',
            name='colorurl',
            field=models.ImageField(upload_to='color/', verbose_name='颜色图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gdesc',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gname',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gdname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goodsdetainame', verbose_name='属性名称'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gdurl',
            field=models.ImageField(upload_to='goods_details/', verbose_name='属性图片'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='所属商品'),
        ),
        migrations.AlterField(
            model_name='goodsdetainame',
            name='gname',
            field=models.CharField(max_length=30, verbose_name='属性名称'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.PositiveIntegerField(verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='size',
            name='sname',
            field=models.CharField(max_length=10, verbose_name='尺寸名称'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('goods', 'color', 'size')},
        ),
    ]
