# Generated by Django 5.2.8 on 2025-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gdesc',
            field=models.CharField(max_length=100, verbose_name='商品描述'),
        ),
    ]
