"""
Django settings for pyshop project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*b#)_i=@)34o!3)7lp0r1*5@*=^jq0yydolo!*4vffdohjs408'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'products', 
    'cart', 
    'users',
    'recommendations',
    'orders'
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pyshop.urls'

TEMPLATES = [
    {
        # 指定模板引擎：使用Django自带的模板后端
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 模板目录列表：Django会按顺序在这些目录中查找模板文件
        'DIRS': [BASE_DIR / "templates"],  # 全局模板目录（存放公共母版base.html）
        'APP_DIRS': True,  # 自动搜索每个应用下的"templates"目录（应用专属模板）
        # 模板上下文处理器：向所有模板传递默认变量（如user、request等）
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 调试模式上下文
                'django.template.context_processors.request',  # 传递request对象给模板
                'django.contrib.auth.context_processors.auth',  # 传递user对象给模板（判断登录状态）
                'django.contrib.messages.context_processors.messages',  # 传递消息提示给模板
            ],
        },
    },
]

WSGI_APPLICATION = 'pyshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'#2025/12/27/23：36添加


# 自定义Admin站点，隐藏无关应用
ADMIN_REORDER = [
    # 只显示核心模块，顺序自定义
    {'app': 'products', 'models': ['products.Product', 'products.Category']},
    {'app': 'orders', 'models': ['orders.Order', 'orders.OrderItem']},
    # 隐藏 users/cart 等模块
]