# Generated by Django 5.2.8 on 2025-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已上架'), ('out_of_stock', '缺货'), ('out_of_stock', '缺货'), ('discontinued', '已下架')], default='draft', max_length=20, verbose_name='商品状态'),
        ),
    ]
